# Generated by Django 3.2.16 on 2023-03-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
    ]
